kvm.init: check for Xauth file for SDL

diff --git a/kvm.init b/kvm.init
--- a/kvm.init
+++ b/kvm.init
@@ -146,6 +146,14 @@ _cfgcheck(){
 		VM_ENABLE_SDL=false
 	fi
 
+	# check for Xauthority file
+	if ${VM_ENABLE_SDL}; then
+		if ! [ -e /home/${VM_USER}/.Xauthority ]; then
+			ewarn " ** Xauthority file missing. Disabling SDL output"
+			VM_ENABLE_SDL=false
+		fi
+	fi
+
 	if [ -n "${VM_KERNEL}" ] && [ -n "${VM_INITRD}" ]; then
 		# guests can't boot from other devices if vm_kernel/vm_initrd is used
 		VM_BOOT_DEV=""
@@ -569,11 +577,6 @@ start(){
 			/bin/sh -c "TMPDIR="${TMP_DIR}" ${qemu_bin} ${myconfig} >/dev/null"
 	else
 		/bin/sh -c "TMPDIR="${TMP_DIR}" ${qemu_bin} ${myconfig} >/dev/null"
-	fi
-
-#password set spice/vnc
-	if ! [ "$(echo ${VM_REMOTE_ACCESS_SPICE}|cut -d';' -f1)" = "" ]; then
-		echo "set_password spice $(echo ${VM_REMOTE_ACCESS_SPICE}|cut -d';' -f1)" | ${NC} --unix -q1 ${PID_DIR}/${SVCNAME}.sock > /dev/null 2>&1
 	fi
 
 	# remove tap devices if the guest system couldn't be started
