varios bugfixes, change remote access variable handling

diff --git a/kvm.init b/kvm.init
--- a/kvm.init
+++ b/kvm.init
@@ -102,6 +102,9 @@ cfgcheck(){
 
 	local default_msg="Please check your config (${CONF_PATH})"
 
+	local net_user_set=false
+	local net_tap_set=false
+
 	# basic tests/settings
 	[ -d ${PID_DIR} ] || mkdir ${PID_DIR}
 	[ -d ${TMP_DIR} ] || TMP_DIR="/var/tmp"
@@ -147,9 +150,9 @@ cfgcheck(){
 	# 9P directory check
 	if [ -n "${_vm_9pshare}" ]; then
 		for single_9p in ${_vm_9pshare}; do
-			local share_name="$(echo ${single_9p}|cut -d: -f1)"
-			local share_path="$(echo ${single_9p}|cut -d: -f2)"
-			local share_secm="$(echo ${single_9p}|cut -d: -f3)"
+			local share_name="$(echo ${single_9p}|cut -d';' -f1)"
+			local share_path="$(echo ${single_9p}|cut -d';' -f2)"
+			local share_secm="$(echo ${single_9p}|cut -d';' -f3)"
 			
 			if [ -z ${share_name} ] || ! [ -e ${share_path} ]; then
 				eerror "No name given or Path does not exist. ${default_msg}"
@@ -159,21 +162,21 @@ cfgcheck(){
 			if [ -z ${share_secm} ]; then
 				share_secm="none"
 			fi
-			VM_9P="${VM_9P} ${share_name}:${share_path}:${share_secm}"
+			VM_9P="${VM_9P} ${share_name};${share_path};${share_secm}"
 		done
 	fi
 
 	# image checks/default settings
 	if [ -n "${_vm_harddisk}" ]; then
 		for single_hd in ${_vm_harddisk}; do
-			local hd_path="$(echo ${single_hd}|cut -d: -f1)"
-			local hd_if="$(echo ${single_hd}|cut -d: -f2)"
-			local hd_cache="$(echo ${single_hd}|cut -d: -f3)"
-			local hd_aio="$(echo ${single_hd}|cut -d: -f4)"
+			local hd_path="$(echo ${single_hd}|cut -d';' -f1)"
+			local hd_if="$(echo ${single_hd}|cut -d';' -f2)"
+			local hd_cache="$(echo ${single_hd}|cut -d';' -f3)"
+			local hd_aio="$(echo ${single_hd}|cut -d';' -f4)"
 
-			if [ -z "${hd_path}" ] || [ -e "${hd_path}" ]; then
-				ewarn " ** ${hd_path} not found. ${default_msg}"
-				continue
+			if [ -z "${hd_path}" ] || ! [ -e "${hd_path}" ]; then
+				eerror "${hd_path} not found. ${default_msg}"
+				return 1
 			fi
 			# check if image is already running
 			if ! scan_running_vm "${hd_path}"; then
@@ -187,7 +190,7 @@ cfgcheck(){
 			# set image format to raw if lvm partition is used
 			[ -b "${hd_path}" ] && hd_path="${hd_path},format=raw"
 
-			VM_HD="${VM_HD} ${hd_path}:${hd_if}:${hd_cache}:${hd_aio}"
+			VM_HD="${VM_HD} ${hd_path};${hd_if};${hd_cache};${hd_aio}"
 		done
 	fi
 
@@ -195,10 +198,11 @@ cfgcheck(){
 	if [ -z "${_vm_interfaces}" ]; then
 		VM_REMOTE_ACCESS_LISTEN_IP="127.0.0.1"
 	else
+		local id=0
 		for single_net in ${_vm_interfaces}; do
-			local net_typ="$(echo ${single_net}|cut -d: -f1)"
-			local net_mac="$(echo ${single_net}|cut -d: -f2)"
-			local net_drv="$(echo ${single_net}|cut -d: -f3)"
+			local net_typ="$(echo ${single_net}|cut -d';' -f1)"
+			local net_mac="$(echo ${single_net}|cut -d';' -f2)"
+			local net_drv="$(echo ${single_net}|cut -d';' -f3)"
 
 			# set default network driver
 			[ -z "${net_drv}" ] && net_drv="rtl8139"
@@ -230,7 +234,6 @@ cfgcheck(){
 						return 1
 					fi
 					# get the guest_nummber for qtap...
-					local id=0;
 					while (${BRCTL} show | egrep qtap${id} >/dev/null 2>&1); do
 						id=$(expr ${id} + 1)
 					done
@@ -239,23 +242,22 @@ cfgcheck(){
 						eerror "Maximum number of network connections reached. Please increase the MAX_QTAP variable."
 						return 1
 					fi
+					VM_NET="${VM_NET} ${net_typ};${net_mac};${net_drv};${id}"
 					;;
 				user)
 					if (${net_user_set}); then
 						eerror "Network typ user can only be used once. ${default_msg}"
 						return 1
 					fi
-					id="user_net"
 					net_user_set=true
+					VM_NET="${VM_NET} ${net_typ};${net_mac};${net_drv};usernet"
 					;;
 				*)
 					ewarn "** Unknow Network Typ. Network will be disabled"
 					continue
 					;;
 			esac
-
-			VM_NET="${VM_NET} ${net_typ}:${net_mac}:${net_drv}:${id}"
-
+			id=$(expr ${id} + 1)
 		done
 
 		if (${net_user_set}) && ! (${net_tap_set}); then
@@ -271,24 +273,32 @@ cfgcheck(){
 
 	# remote access checks
 	if [ -n "${VM_REMOTE_ACCESS}" ]; then
+		local remote_typ="$(echo ${VM_REMOTE_ACCESS}|cut -d';' -f1)"
+		local remote_ip="$(echo ${VM_REMOTE_ACCESS}|cut -d';' -f2)"
+		local remote_port="$(echo ${VM_REMOTE_ACCESS}|cut -d';' -f3)"
+
 		# set listening ip
-		if [ -z "${VM_REMOTE_ACCESS_LISTEN_IP}" ]; then
+		if [ -z "${remote_ip}" ]; then
 			VM_REMOTE_ACCESS_LISTEN_IP="`${IP} address show ${BRDEV} \
 				| egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}' \
 				| head -n1`"
+		else
+			VM_REMOTE_ACCESS_LISTEN_IP=${remote_ip}
 		fi
 		# i don't use scan_running_vm here because other programms could use those ports too...
 		# have to check with netstat if a port is free
-		if [ -z "${VM_REMOTE_ACCESS_PORT}" ]; then
+		if [ -z "${remote_port}" ]; then
 			local port_nr=0
 			while $(netstat -nat | egrep "${VM_REMOTE_ACCESS_LISTEN_IP}:580${port_nr}[^0-9]" >/dev/null); do
 				port_nr=$(expr ${port_nr} + 1)
 			done
 			VM_REMOTE_ACCESS_PORT="580${port_nr}"
 		# check port if it was manuel set
-		elif $(netstat -nat | egrep "${VM_REMOTE_ACCESS_LISTEN_IP}:${VM_REMOTE_ACCESS_PORT}[^0-9]" >/dev/null); then
+		elif $(netstat -nat | egrep "${VM_REMOTE_ACCESS_LISTEN_IP}:${remote_port}[^0-9]" >/dev/null); then
 			eerror "Port is already in use. ${default_msg}"
 			return 1
+		else
+			VM_REMOTE_ACCESS_PORT=${remote_port}
 		fi
 	else
 		ewarn " ** Remote access disabled"
@@ -341,17 +351,14 @@ myconfig(){
 
 	# remote access settings
 	if [ -n "${VM_REMOTE_ACCESS}" ]; then
-		case ${VM_REMOTE_ACCESS} in
+		case "$(echo ${VM_REMOTE_ACCESS}|cut -d';' -f1)" in
 			spice|SPICE)
 				VM_DISPLAY="qxl"
 				[ -n "${VM_REMOTE_ACCESS_PW}" ] || VM_REMOTE_ACCESS_PW="\"\",disable-ticketing"
 				myconfig="${myconfig} -spice port=${VM_REMOTE_ACCESS_PORT},addr=${VM_REMOTE_ACCESS_LISTEN_IP},password=${VM_REMOTE_ACCESS_PW}"
 				;;
 			vnc|VNC)
-				# reason for changing the port to such a strange number:
-				# https://bugs.gentoo.org/show_bug.cgi?id=461744
-				# https://bugs.launchpad.net/qemu/+bug/1089496
-				VM_REMOTE_ACCESS_PORT=$(expr ${VM_REMOTE_ACCESS_PORT} + 59635 - 65535)
+				VM_REMOTE_ACCESS_PORT=$(expr ${VM_REMOTE_ACCESS_PORT} - 5800)
 				myconfig="${myconfig} -vnc ${VM_REMOTE_ACCESS_LISTEN_IP}:${VM_REMOTE_ACCESS_PORT}"
 				;;
 			*)
@@ -366,10 +373,10 @@ myconfig(){
 	# enable/disable harddisks
 	if [ -n "${VM_HD}" ]; then
 		for single_hd in ${VM_HD}; do
-			local hd_path="$(echo ${single_hd}|cut -d: -f1)"
-			local hd_if="$(echo ${single_hd}|cut -d: -f2)"
-			local hd_cache="$(echo ${single_hd}|cut -d: -f3)"
-			local hd_aio="$(echo ${single_hd}|cut -d: -f4)"
+			local hd_path="$(echo ${single_hd}|cut -d';' -f1)"
+			local hd_if="$(echo ${single_hd}|cut -d';' -f2)"
+			local hd_cache="$(echo ${single_hd}|cut -d';' -f3)"
+			local hd_aio="$(echo ${single_hd}|cut -d';' -f4)"
 
 			myconfig="${myconfig} \
 			-drive file=${hd_path},if=${hd_if},cache=${hd_cache},aio=${hd_aio}"
@@ -379,10 +386,10 @@ myconfig(){
 	# network settings
 	if [ -n "${VM_NET}" ]; then
 		for single_net in ${VM_NET}; do
-			local net_typ="$(echo ${single_net}|cut -d: -f1)"
-			local net_mac="$(echo ${single_net}|cut -d: -f2)"
-			local net_drv="$(echo ${single_net}|cut -d: -f3)"
-			local net_id="$(echo ${single_net}|cut -d: -f4)"
+			local net_typ="$(echo ${single_net}|cut -d';' -f1)"
+			local net_mac="$(echo ${single_net}|cut -d';' -f2)"
+			local net_drv="$(echo ${single_net}|cut -d';' -f3)"
+			local net_id="$(echo ${single_net}|cut -d';' -f4)"
 
 			case ${net_typ} in
 				tap)
@@ -405,9 +412,9 @@ myconfig(){
 	if [ -n "${VM_9P}" ]; then
 		local id=0
 		for single_9p in ${VM_9P}; do
-			local share_name="$(echo ${single_9p}|cut -d: -f1)"
-			local share_path="$(echo ${single_9p}|cut -d: -f2)"
-			local share_secm="$(echo ${single_9p}|cut -d: -f3)"
+			local share_name="$(echo ${single_9p}|cut -d';' -f1)"
+			local share_path="$(echo ${single_9p}|cut -d';' -f2)"
+			local share_secm="$(echo ${single_9p}|cut -d';' -f3)"
 			myconfig="${myconfig} \
 				-fsdev local,id="${VM_NAME}_9p_${id}",path="${share_path}",security_model="${share_secm}" \
 				-device virtio-9p-pci,fsdev="${VM_NAME}_9p_${id}",mount_tag="${share_name}""
@@ -439,18 +446,15 @@ stop_tap_device(){
 	einfo "Bring qtap${stop_id} interface down"
 	${IP} link set dev qtap${stop_id} down
 	eend $? "Failed to bring qtap${stop_id} down"
-
-	einfo " Unlinking the bridge interface with qtap${stop_id}"
 	${BRCTL} delif ${BRDEV} qtap${stop_id}
 	eend $? "Failed to unlink the bridge interface to qtap${stop_id}"
-
 	sleep 2
-	einfo " Removing the tap interface: qtap${stop_id}"
 	${IP} tuntap del qtap${stop_id} mode tap
 }
 
 start(){
 	local qemu_bin
+	local tap_enabled=false
 
 	# Test if requested arch is available in qemu
 	# defaulting to system arch
@@ -466,31 +470,32 @@ start(){
 	myconfig || return 1
 	if [ -n "${VM_NET}" ]; then
 		for single_net in ${VM_NET}; do
-			local net_typ="$(echo ${single_net}|cut -d: -f1)"
-			local net_id="$(echo ${single_net}|cut -d: -f4)"
+			local net_typ="$(echo ${single_net}|cut -d';' -f1)"
+			local net_id="$(echo ${single_net}|cut -d';' -f4)"
 	
 			if [ ${net_typ} = "tap" ]; then
 				tap_enabled=true
-				einfo "Setting up the tap interface: qtap${start_id}"
-				${IP} tuntap add dev qtap${start_id} mode tap user ${VM_USER} || return 1
-				einfo " Linking the bridge interface with qtap${start_id}"
-				${BRCTL} addif ${BRDEV} qtap${start_id} || return 1
-				einfo " Bring qtap${start_id} interface up"
-				${IP} link set dev qtap${start_id} up promisc on || return 1
+				einfo "Setting up the tap interface: qtap${net_id}"
+				${IP} tuntap add dev qtap${net_id} mode tap user ${VM_USER} || return 1
+				${BRCTL} addif ${BRDEV} qtap${net_id} || return 1
+				${IP} link set dev qtap${net_id} up promisc on || return 1
 			fi
 		done
 	fi
 
 	# print some important information
 	ebegin "Starting ${VM_NAME}..."
-	[ -n "${VM_REMOTE_ACCESS}" ] && ebegin " remote access via ${VM_REMOTE_ACCESS} on ${VM_REMOTE_ACCESS_LISTEN_IP}:${VM_REMOTE_ACCESS_PORT}"
+	if [ -n "${VM_REMOTE_ACCESS}" ]; then
+		[ "$(echo ${VM_REMOTE_ACCESS}|cut -d';' -f1)" = vnc ] && VM_REMOTE_ACCESS_PORT=$(expr ${VM_REMOTE_ACCESS_PORT} + 5900)
+		ebegin " remote access via $(echo ${VM_REMOTE_ACCESS} | cut -d';' -f1) on ${VM_REMOTE_ACCESS_LISTEN_IP}:${VM_REMOTE_ACCESS_PORT}"
+	fi
 	if [ -n "${VM_9P}" ]; then
 		ebegin " Enabled shared folders:"
 		for single_9p in ${VM_9P}; do
-			local share_name="$(echo ${single_9p}|cut -d: -f1)"
-			local share_path="$(echo ${single_9p}|cut -d: -f2)"
-			local share_secm="$(echo ${single_9p}|cut -d: -f3)"
-			ebegin "  == ${share_path} / ${share_name} / ${share_secm}"
+			local share_name="$(echo ${single_9p}|cut -d';' -f1)"
+			local share_path="$(echo ${single_9p}|cut -d';' -f2)"
+			local share_secm="$(echo ${single_9p}|cut -d';' -f3)"
+			ebegin "  ${share_path} via ${share_name}(${share_secm})"
 		done
 	fi
 
@@ -512,15 +517,15 @@ start(){
 	# Start the Virtual Machine
 	# start guest with /bin/sh, otherwise qemu breaks with
 	# multiple append statements (probably a qemu or runscript bug)
-	/bin/sh/ -c "TMPDIR="${TMP_DIR}" ${qemu_bin} ${myconfig} >/dev/null"
+	/bin/sh -c "TMPDIR="${TMP_DIR}" ${qemu_bin} ${myconfig} >/dev/null"
 
 	# remove tap devices if the guest system couldn't be started
 	if [ "$?" != "0" ]; then
 		if (${tap_enabled}); then
 			eerror "Failed to start ${VM_NAME}, shuting down qtap devices"
 			for single_net in ${VM_NET}; do
-				local net_typ="$(echo ${single_net}|cut -d: -f1)"
-				local net_id="$(echo ${single_net}|cut -d: -f4)"
+				local net_typ="$(echo ${single_net}|cut -d';' -f1)"
+				local net_id="$(echo ${single_net}|cut -d';' -f4)"
 				[ ${net_typ} = "tap" ] && stop_tap_device ${net_id}
 			done
 		fi
@@ -567,6 +572,7 @@ stop(){
 			printf "."
 		done
 		echo
+		# remove tap interfaces
 		for tap_id in ${stop_id}; do
 			if ! $(${BRCTL} show|grep qtap${tap_id} >/dev/null); then
 				ewarn "Couldn't find a qtap device. Please run \"/etc/init.d/kvm.init tapdel\""
@@ -574,8 +580,6 @@ stop(){
 			fi
 			stop_tap_device ${tap_id}
 		done
-		# stop qtap device
-		[ -z "${stop_id}" ] || stop_tap_device
 
 		# remove remaining files
 		rm -rf ${PID_DIR}/${VM_NAME}.pid
