qvm,qemucc: better root handling, cleanups, improved help

diff --git a/qemucc b/qemucc
--- a/qemucc
+++ b/qemucc
@@ -43,8 +43,11 @@ if [ "${2}" = "/etc/conf.d/kvm.${2##*.}" ]; then
 else
 	VM_NAME="${2##*/}"
 fi
+
 # default message
 DEFAULT_MSG="Please check your config (${2})"
+
+SET_USER="true"
 
 loginfo() { while IFS='' read -r line; do >&2 echo -e "${YELLOW} * ${NC}${line}"; done }
 logerr() { while IFS='' read -r line; do >&2 echo -e "${LIGHTRED} * ${NC}${line}"; done }
@@ -56,7 +59,12 @@ EOM
 usage() {
 	echo -e "$0"
 	echo
-	echo -e "$0" /path/to/config.file
+	echo -e "Check a qemu-init config file for it's correctness"
+	echo
+	echo -e "$0 -c|--check /path/to/config.file\t\tcheck config file and print out the qemu runconfig"
+	echo -e "$0 --checkandcreate /path/to/config.file\t\tlike -c|--check but actually create tap devices if needed (root required)"
+	echo -e "$0 -s|--spice /path/to/config.file\t\tprint out spice password if set"
+	echo -e "$0 -v|--vnc /path/to/config.file\t\t\tprint out vnc password if set"
 }
 
 _check_remote_access_port(){
@@ -129,66 +137,47 @@ _cfg_network_check(){
 					echo "No bridge device setup! ${DEFAULT_MSG}" | (logerr)
 					return 1
 				fi
-				# enumerate qtap id only works when using the script as root
-				if [ "$(id -u)" = 0 ]; then
-					# check for max_vms
-					if [ ${_net_id} -ge ${MAX_QTAP} ]; then
-						echo "Maximum number of network connections reached. Please increase the MAX_QTAP variable." | (logerr)
+				# check for max_vms
+				if [ ${_net_id} -ge ${MAX_QTAP} ]; then
+					echo "Maximum number of network connections reached. Please increase the MAX_QTAP variable." | (logerr)
+					return 1
+				fi
+				if [ -n "${net_qtp}" ]; then
+					if ! [ -f /sys/class/net/${net_qtp}/tun_flags ]; then
+						echo "\"${net_qtp}\" is not a tun/tap device. ${DEFAULT_MSG}" | (logerr)
 						return 1
-					fi
-					if [ -n "${net_qtp}" ]; then
-						if ! [ -f /sys/class/net/${net_qtp}/tun_flags ]; then
-							echo "\"${net_qtp}\" is not a tun/tap device. ${DEFAULT_MSG}" | (logerr)
-							return 1
-						else
-							if ${_random_mac}; then
-								echo "mac address \"${net_mac}\" for ${net_qtp} is random and will be lost after shutdown" | (loginfo)
-							fi
-							VM_NET="${VM_NET} \
-								-netdev tap,id="${VM_NAME}_${_net_id}",ifname=${net_qtp},script=no,downscript=no${_vhost_set} \
-								-device ${net_drv},netdev="${VM_NAME}_${_net_id}",mac=${net_mac}"
-						fi
 					else
-						# get the guest_nummber for qtap...
-						while (${BRIDGE} link | egrep -o qtap${_net_id} >/dev/null 2>&1); do
-							_net_id=$(expr ${_net_id} + 1)
-						done
 						if ${_random_mac}; then
-							echo "mac address \"${net_mac}\" for qtap${_net_id} is random and will be lost after shutdown" | (loginfo)
+							echo "mac address \"${net_mac}\" for ${net_qtp} is random and will be lost after shutdown" | (loginfo)
 						fi
 						VM_NET="${VM_NET} \
-							-netdev tap,id="${VM_NAME}_${_net_id}",ifname=qtap${_net_id},script=no,downscript=no${_vhost_set} \
+							-netdev tap,id="${VM_NAME}_${_net_id}",ifname=${net_qtp},script=no,downscript=no${_vhost_set} \
 							-device ${net_drv},netdev="${VM_NAME}_${_net_id}",mac=${net_mac}"
-						# this is the network start script which later gets executed via /bin/sh
-						# the ';' at the last line makes sure that there is a correct
-						# linebreak
-						read -r -d '' VM_TAPSTART <<- EOM
-							${IP} tuntap add dev qtap${_net_id} mode tap user ${VM_USER}
-							${IP} link set qtap${_net_id} master ${net_brd}
-							${IP} link set dev qtap${_net_id} up promisc on
-							echo "qtap${_net_id} " >> ${PID_DIR}/${VM_NAME}.net ;
-						EOM
-						VM_NETSTART+="${VM_TAPSTART}"
 					fi
 				else
-					if [ -n "${net_qtp}" ]; then
-						if ! [ -f /sys/class/net/${net_qtp}/tun_flags ]; then
-							echo "\"${net_qtp}\" is not a tun/tap device. ${DEFAULT_MSG}" | (loginfo)
-							return 1
-						else
-							if ${_random_mac}; then
-								echo "mac address \"${net_mac}\" for ${net_qtp} is random and will be lost after shutdown" | (loginfo)
-							fi
-							VM_NET="${VM_NET} \
-								-netdev tap,id="${VM_NAME}_${_net_id}",ifname=${net_qtp},script=no,downscript=no \
-								-device ${net_drv},netdev="${VM_NAME}_${_net_id}",mac=${net_mac}"
-						fi
-					else
-						echo "Part of the network config doesn't include a definded tap device. This means you have following options: " | (logerr)
-						echo " - run the script as root. This way tap devices are created automatically by the script." | (logerr)
-						echo " - create tap devices manually (only possible as root, see: qvm -h) and update the configuration" | (logerr)
-						return 1
+					if ! [ "$(id -u)" = 0 ]; then
+						echo "Warning: Need to create tap devices. Root access needed!" | (loginfo)
 					fi
+					# get the guest_nummber for qtap...
+					while (${BRIDGE} link | egrep -o qtap${_net_id} >/dev/null 2>&1); do
+						_net_id=$(expr ${_net_id} + 1)
+					done
+					if ${_random_mac}; then
+						echo "mac address \"${net_mac}\" for qtap${_net_id} is random and will be lost after shutdown" | (loginfo)
+					fi
+					VM_NET="${VM_NET} \
+						-netdev tap,id="${VM_NAME}_${_net_id}",ifname=qtap${_net_id},script=no,downscript=no${_vhost_set} \
+						-device ${net_drv},netdev="${VM_NAME}_${_net_id}",mac=${net_mac}"
+					# this is the network start script which later gets executed via /bin/sh
+					# the ';' at the last line makes sure that there is a correct
+					# linebreak
+					read -r -d '' VM_TAPSTART <<- EOM
+						${IP} tuntap add dev qtap${_net_id} mode tap user ${VM_USER}
+						${IP} link set qtap${_net_id} master ${net_brd}
+						${IP} link set dev qtap${_net_id} up promisc on
+						echo "qtap${_net_id} " >> ${PID_DIR}/${VM_NAME}.net ;
+					EOM
+					VM_NETSTART+="${VM_TAPSTART}"
 				fi
 				;;
 			user)
@@ -198,7 +187,7 @@ _cfg_network_check(){
 				fi
 				_net_user_set=true
 				if ${_random_mac}; then
-					echo "mac address \"${net_mac}\" for ${VM_NAME} is random and will be lost after shutdown" | (loginfo)
+					echo "mac address \"${net_mac}\" for usernet is random and will be lost after shutdown" | (loginfo)
 				fi
 				VM_NET="${VM_NET} \
 						-netdev user,id=${VM_NAME}_${_net_id} \
@@ -364,8 +353,8 @@ _cfgcheck(){
 			VM_ENABLE_GL=false
 		fi
 	else
-		# if run as non root, unset VM_USER so that the script avoids using -runas
-		VM_USER=""
+		# if run as non root, set SET_USER to false to avoid using -runas
+		SET_USER="false"
 	fi
 
 	# check if SDL can be enabled (needs .Xauthority file)
@@ -437,7 +426,7 @@ _myconfig(){
 		-machine ${VM_MACHINE:-pc} \
 		-k ${VM_LC:-de}"
 
-	[ -z "${VM_USER}" ] || myconfig="${myconfig} -runas ${VM_USER}"
+	${SET_USER} && myconfig="${myconfig} -runas ${VM_USER}"
 	[ -z "${VM_CPU}" ] || myconfig="${myconfig} -cpu ${VM_CPU}"
 
 	if [ -n "${VM_KERNEL}" ]; then
@@ -528,13 +517,9 @@ get_vnc_pw() {
 	fi
 }
 
-get_user() {
-	echo ${VM_USER}
-}
-
 if [ $# -lt 2 ]; then usage; exit; fi
 
-OPTS=$(getopt -o c:s:v:u: --long check:,spice:,vnc:,user:,checkandcreate: -n 'qvm' -- "$@")
+OPTS=$(getopt -o c:s:v: --long check:,spice:,vnc:,checkandcreate: -n 'qvm' -- "$@")
 eval set -- "$OPTS"
 
 myconfig=""
@@ -545,7 +530,12 @@ while true; do
 			case "$2" in
 				"") shift 2 ;;
 				*)
-					source $2
+					if [ -r ${2} ]; then
+						source $2
+					else
+						echo "couldn't read ${2}. Permission denied"
+						exit 1
+					fi
 					if _cfgcheck; then
 						_myconfig
 						# if cfgcheck passed and myconfig is generated start to create the
@@ -553,7 +543,12 @@ while true; do
 						case "$1" in
 							--checkandcreate)
 								if [ -n "${VM_NETSTART}" ]; then
-									su -l root -c "${VM_NETSTART}"
+									if [ -e "${PID_DIR}/${VM_NAME}.net" ]; then
+										echo "${PID_DIR}/${VM_NAME}.net already exists. Aborting tap interface creation!" | (logerr)
+										exit 1
+									else
+										su -l root -c "${VM_NETSTART}"
+									fi
 								fi
 								;;
 							*)
@@ -581,11 +576,6 @@ while true; do
 			case "$2" in
 				"") shift 2 ;;
 				*) source $2 ; get_vnc_pw ; shift 2 ;;
-			esac ;;
-		-u|--user)
-			case "$2" in
-				"") shift 2 ;;
-				*) source $2 ; get_user ; shift 2 ;;
 			esac ;;
 		--) shift ; break ;;
 		*) echo "Internal error!" | (logerr) ; exit 1 ;;
diff --git a/qvm b/qvm
--- a/qvm
+++ b/qvm
@@ -31,7 +31,6 @@ IP="/bin/ip"									# sys-apps/iproute2
 NC="/usr/bin/nc"							# net-analyzer/openbsd-netcat
 QGA="/usr/bin/qemu-ga-client"	# app-emulation/qemu[pyhton]
 LSOF="/usr/bin/lsof"					# sys-process/lsof
-
 QEMUCC="/home/ai/coding/qemucc"
 
 # check PID_DIR
@@ -148,24 +147,25 @@ _vm_memory(){
 
 _stop_tap_devices() {
 	local vmname="${1}"
+	local ready_to_delete=true
 
 	# find all linked qtap devices
 	if [ -e "${PID_DIR}/${vmname}.net" ]; then
 		for qtap_id in $(cat ${PID_DIR}/${vmname}.net); do
-			# warn if qtap device doesn't exist anymore
-			if ! $(${BRIDGE} link|grep -o ${qtap_id} >/dev/null); then
-				echo "Couldn't find ${qtap_id} device."
-				continue
+			# check if qtap_id is a tap device
+			delete_network bridge,${qtap_id}
+			if [ -d /sys/class/net/${qtap_id}/ ]; then
+				ready_to_delete=false
 			fi
-			# remove tap interfaces
-			echo "Removing ${qtap_id} interface"
-			${IP} link set dev ${qtap_id} down
-			${IP} link set ${qtap_id} nomaster
-			${IP} tuntap del ${qtap_id} mode tap
 		done
 		# better safe then sorry
 		if [ -e  "${PID_DIR}/${vmname}.net" ]; then
-			rm -rf ${PID_DIR}/${vmname}.net
+			# only delete this file if we could remove all interfaces
+			if ${ready_to_delete}; then
+				rm -rf ${PID_DIR}/${vmname}.net
+			else
+				echo "Warning: couldn't delete all network interfaces."
+			fi
 		fi
 	fi
 }
@@ -196,10 +196,10 @@ vm_list() {
 		if [ -n "${CFG_DIR}" ]; then
 			echo " Local VMs:"
 			for i in $(find ${CFG_DIR} -type f); do
-				if [ -e ${PID_DIR}/${i} ]; then
-					echo "  U ${i}$(cat ${PID_DIR}/${i})"
+				if [ -e ${PID_DIR}/${i##*/}.pid ]; then
+					echo "  U ${i##*/} (PID: $(cat ${PID_DIR}/${i##*/}.pid))"
 				else
-					echo "  D ${i}"
+					echo "  D ${i##*/}"
 				fi
 			done
 		fi
@@ -268,7 +268,7 @@ create_network() {
 		su -l root -c "${CREATE_TAP}"
 	#elif
 	else
-		echo "Cannot create ${_type}. Unknown device"
+		echo "Cannot create ${_name}. ${_type} is not support"
 		exit 1
 	fi
 }
@@ -281,23 +281,27 @@ delete_network() {
 		exit 1
 	fi
 
-	if [ -d /sys/class/net/${_type}/bridge/ ]; then
-		if ! $(${BRIDGE} link|grep -o ${_name} >/dev/null); then
-			echo "Couldn't find ${_name} device. Not trying to remove it."
-			exit 1
-		fi
+	if [ -e /sys/class/net/${_name}/tun_flags ]; then
 		# remove tap interfaces
 		echo "Removing ${_name} interface"
-		read -r -d '' DELETE_TAP <<- EOM
-			${IP} link set dev ${_name} down
-			${IP} link set ${_name} nomaster
+		if [ "$(cat /sys/class/net/${_name}/owner)" = "$(id -u)" ]; then
 			${IP} tuntap del ${_name} mode tap
-		EOM
-		su -l root -c "${DELETE_TAP}"
+		else
+			# print a warning if tap devices doesn't belong to user (only for non-root
+			# users)
+			if ! [ $(id -u) = 0 ]; then
+				echo "Warning: ${_name} belongs to user: $(cat /sys/class/net/${_name}/owner)"
+			fi
+			read -r -d '' DELETE_TAP <<- EOM
+				${IP} link set dev ${_name} down
+				${IP} link set ${_name} nomaster
+				${IP} tuntap del ${_name} mode tap
+			EOM
+			su -l root -c "${DELETE_TAP}"
+		fi
 	#elif
 	else
-		echo "Cannot create ${_type}. Unknown device"
-		exit 1
+		echo "Couldn't remove ${_name}. Unknown device"
 	fi
 }
 
@@ -339,11 +343,14 @@ vm_freeze_thaw(){
 
 vm_start(){
 	local vm_config_file=${1}
+	if [ $(id -u) = 0 ] && [ -z "${CFG_DIR}" ]; then
+		CFG_DIR="/etc/conf.d/kvm."
+	fi
 
 	if ! [ -f ${vm_config_file} ]; then
-		if [ -f "${CFG_DIR}/${vm_config_file}" ]; then
+		if [ -f "${CFG_DIR}${vm_config_file}" ]; then
 			vmname="${vm_config_file}"
-			vm_config_file="${CFG_DIR}/${vm_config_file}"
+			vm_config_file="${CFG_DIR}${vm_config_file}"
 		else
 			echo "config file \"${CFG_DIR}${vm_config_file}\" not found."
 			exit 1
@@ -438,11 +445,11 @@ vm_stop(){
 		echo "Couldn't find the process for ${vmname}, guest might already down."
 	fi
 
+	_stop_tap_devices ${vmname}
 
+	# for some reason when running as root qemu doesn't clean up pid/sock files
+	# after we stopped a vm. So lets clean them up manually.
 	if [ $(id -u) = 0 ]; then
-		_stop_tap_devices ${vmname}
-		# for some reason when running as root qemu doesn't clean up pid/sock files
-		# after we stopped a vm. So lets clean them up manually.
 		for f in qga.sock sock pid; do
 			if [ -e "${PID_DIR}/${vmname}.${f}" ]; then
 				rm ${PID_DIR}/${vmname}.${f}
